import { PrismaClient } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Starting database seed...')

  // Create default user
  const hashedPassword = await bcrypt.hash('password123', 12)
  
  const defaultUser = await prisma.user.upsert({
    where: { email: 'demo@eacon.app' },
    update: {},
    create: {
      email: 'demo@eacon.app',
      name: 'Demo User',
      password: hashedPassword,
      tokens: 5000,
      createdAt: new Date(),
    },
  })

  console.log('👤 Created default user:', defaultUser.email)

  // Create categories
  const categories = [
    {
      name: 'social-media',
      displayName: 'Social Media',
      description: 'Templates for social media platforms',
      icon: '📱',
      color: '#3B82F6',
      isActive: true,
      sortOrder: 1,
    },
    {
      name: 'business',
      displayName: 'Business',
      description: 'Professional business templates',
      icon: '💼',
      color: '#1F2937',
      isActive: true,
      sortOrder: 2,
    },
    {
      name: 'lifestyle',
      displayName: 'Lifestyle',
      description: 'Lifestyle and personal content',
      icon: '🌟',
      color: '#F59E0B',
      isActive: true,
      sortOrder: 3,
    },
    {
      name: 'food',
      displayName: 'Food & Drinks',
      description: 'Food photography and culinary content',
      icon: '🍽️',
      color: '#EF4444',
      isActive: true,
      sortOrder: 4,
    },
    {
      name: 'travel',
      displayName: 'Travel',
      description: 'Travel and adventure content',
      icon: '✈️',
      color: '#10B981',
      isActive: true,
      sortOrder: 5,
    },
    {
      name: 'fashion',
      displayName: 'Fashion',
      description: 'Fashion and beauty content',
      icon: '👗',
      color: '#EC4899',
      isActive: true,
      sortOrder: 6,
    },
    {
      name: 'technology',
      displayName: 'Technology',
      description: 'Tech and digital content',
      icon: '💻',
      color: '#6366F1',
      isActive: true,
      sortOrder: 7,
    },
    {
      name: 'art',
      displayName: 'Art & Design',
      description: 'Artistic and creative content',
      icon: '🎨',
      color: '#8B5CF6',
      isActive: true,
      sortOrder: 8,
    },
    {
      name: 'transform',
      displayName: 'Transform',
      description: 'Transform your photos with viral trends',
      icon: '✨',
      color: '#F97316',
      isActive: true,
      sortOrder: 9,
    },
  ]

  console.log('📂 Creating categories...')
  for (const category of categories) {
    await prisma.category.upsert({
      where: { name: category.name },
      update: category,
      create: category,
    })
  }

  // 50 Premium Viral Trends Templates (cost: 50-60 tokens, unlockCost: 300-400 tokens)
  const templates = [
    // TOP VIRAL TRENDS - Premium Collection
    {
      title: 'Siren Eyes Makeup Viral',
      description: 'Trang điểm mắt siren đang viral toàn cầu trên TikTok với 671M views',
      prompt: 'Stunning Asian woman with perfect siren eyes makeup, dramatic dark winged eyeliner extending to temples, smoky bronze eyeshadow, sultry mysterious gaze, half-closed seductive eyes, professional studio lighting, beauty portrait photography, HD quality',
      style: 'realistic',
      platform: 'TikTok',
      tags: ['siren eyes', 'viral makeup', 'tiktok trend', 'seductive', 'beauty'],
      cost: 55,
      unlockCost: 180,
      category: 'fashion',
      isActive: true,
    },
    {
      title: 'Dark Feminine Era Aesthetic',
      description: 'Phong cách dark feminine đang thống trị social media',
      prompt: 'Dark feminine aesthetic woman, mysterious black outfit, gothic jewelry, dramatic shadows, confident powerful pose, luxurious dark background, smoky makeup, seductive energy, high fashion photography',
      style: 'dramatic',
      platform: 'Instagram',
      tags: ['dark feminine', 'gothic', 'viral aesthetic', 'mysterious', 'powerful'],
      cost: 58,
      unlockCost: 190,
      category: 'fashion',
      isActive: true,
    },
    {
      title: 'AI Thối Não Character Viral',
      description: 'Nhân vật AI kỳ quặc như Tung Tung Sahur đang viral với billions views',
      prompt: 'Surreal viral AI character, quirky whimsical design, colorful cartoon style, Tung Tung Sahur inspired, playful bizarre expression, TikTok meme aesthetic, Italian brain rot trend, digital art style',
      style: 'cartoon',
      platform: 'TikTok',
      tags: ['ai character', 'brain rot', 'viral meme', 'tung tung sahur', 'bizarre'],
      cost: 52,
      unlockCost: 175,
      category: 'art',
      isActive: true,
    },
    {
      title: 'Vietnamese Cành Vải Decor Trend',
      description: 'Trend cắm cành vải viral khắp Việt Nam và quốc tế',
      prompt: 'Beautiful Vietnamese lychee branches in elegant ceramic vase, home decoration trend, authentic Vietnamese fruits, natural lighting, aesthetic arrangement, rustic modern interior, cultural pride',
      style: 'natural',
      platform: 'Instagram',
      tags: ['cành vải', 'vietnamese trend', 'home decor', 'viral decoration', 'cultural'],
      cost: 50,
      unlockCost: 160,
      category: 'lifestyle',
      isActive: true,
    },
    {
      title: 'Ao Dai Modern Fashion Viral',
      description: 'Áo dài Việt Nam phiên bản hiện đại viral quốc tế',
      prompt: 'Modern Vietnamese ao dai fashion, elegant young woman, traditional meets contemporary design, flowing silk fabric, cultural heritage pride, beautiful Vietnam landscape background, fashion photography',
      style: 'elegant',
      platform: 'Instagram',
      tags: ['ao dai', 'vietnamese fashion', 'cultural trend', 'modern traditional', 'viral'],
      cost: 60,
      unlockCost: 200,
      category: 'fashion',
      isActive: true,
    },
    {
      title: 'TikTok Dance Trend Viral',
      description: 'Điệu nhảy viral đang thống trị TikTok Việt Nam',
      prompt: 'Young Vietnamese girl performing viral TikTok dance, energetic dynamic pose, trendy outfit, studio lighting, social media content style, fun joyful expression, dance movement',
      style: 'energetic',
      platform: 'TikTok',
      tags: ['tiktok dance', 'viral trend', 'vietnamese youth', 'social media', 'energetic'],
      cost: 53,
      unlockCost: 170,
      category: 'social-media',
      isActive: true,
    },
    {
      title: 'Korean Glass Skin Viral',
      description: 'Làn da thủy tinh Hàn Quốc đang trending toàn cầu',
      prompt: 'Perfect Korean glass skin, dewy glowing complexion, natural fresh makeup, skincare glow, clean beauty aesthetic, soft natural lighting, youthful radiant appearance, K-beauty trend',
      style: 'natural',
      platform: 'Instagram',
      tags: ['korean beauty', 'glass skin', 'k-beauty', 'viral skincare', 'dewy'],
      cost: 57,
      unlockCost: 185,
      category: 'fashion',
      isActive: true,
    },
    {
      title: 'Cottagecore Aesthetic Viral',
      description: 'Phong cách cottagecore đang viral trên toàn thế giới',
      prompt: 'Cottagecore aesthetic, vintage floral dress, peaceful countryside setting, wildflowers meadow, rustic charm, soft golden natural lighting, peaceful dreamy vibe, romantic pastoral',
      style: 'vintage',
      platform: 'Instagram',
      tags: ['cottagecore', 'vintage aesthetic', 'countryside', 'viral lifestyle', 'peaceful'],
      cost: 55,
      unlockCost: 180,
      category: 'lifestyle',
      isActive: true,
    },
    {
      title: 'Y2K Fashion Revival Viral',
      description: 'Thời trang Y2K comeback viral mạnh mẽ trên Gen Z',
      prompt: 'Y2K fashion revival, metallic futuristic clothing, bold neon colors, retro accessories, early 2000s aesthetic, cyber fashion style, trendy nostalgic pose, millennium bug vibes',
      style: 'retro',
      platform: 'Instagram',
      tags: ['y2k fashion', 'retro revival', 'futuristic', 'gen z trend', 'millennium'],
      cost: 58,
      unlockCost: 190,
      category: 'fashion',
      isActive: true,
    },
    {
      title: 'Bubble Tea Art Viral',
      description: 'Nghệ thuật trà sữa đang viral khắp social media',
      prompt: 'Artistic bubble tea presentation, colorful tapioca pearls, creative aesthetic toppings, Instagram-worthy cafe setting, viral food styling, rainbow colors, kawaii presentation',
      style: 'colorful',
      platform: 'Instagram',
      tags: ['bubble tea', 'food art', 'viral beverage', 'aesthetic food', 'kawaii'],
      cost: 51,
      unlockCost: 165,
      category: 'food',
      isActive: true,
    },
    {
      title: 'Vietnamese Street Food Viral',
      description: 'Ẩm thực đường phố Việt Nam viral trên TikTok quốc tế',
      prompt: 'Authentic Vietnamese street food scene, banh mi pho cooking, fresh local ingredients, bustling market atmosphere, cultural food experience, traditional cooking methods, street vendor',
      style: 'authentic',
      platform: 'TikTok',
      tags: ['vietnamese food', 'street food', 'authentic culture', 'viral cuisine', 'traditional'],
      cost: 54,
      unlockCost: 175,
      category: 'food',
      isActive: true,
    },
    {
      title: 'Soft Girl Aesthetic Viral',
      description: 'Phong cách soft girl đang thống trị TikTok và Instagram',
      prompt: 'Soft girl aesthetic, pastel pink colors, cute kawaii clothing, innocent sweet makeup, dreamy background, cloud-like accessories, gentle sweet expression, anime-inspired',
      style: 'cute',
      platform: 'TikTok',
      tags: ['soft girl', 'pastel aesthetic', 'kawaii', 'viral style', 'cute'],
      cost: 56,
      unlockCost: 180,
      category: 'fashion',
      isActive: true,
    },
    {
      title: 'Gaming Girl Streamer Viral',
      description: 'Nữ streamer game đang hot trend trên Twitch và TikTok',
      prompt: 'Female gaming streamer, RGB LED setup, professional streaming equipment, cute gaming chair, colorful neon lights, engaging personality, gaming room aesthetic, modern technology',
      style: 'modern',
      platform: 'Twitch',
      tags: ['gaming streamer', 'rgb setup', 'viral gamer', 'technology', 'streaming'],
      cost: 59,
      unlockCost: 195,
      category: 'technology',
      isActive: true,
    },
    {
      title: 'Latte Art Viral Trend',
      description: 'Nghệ thuật latte đang hot trend trên Instagram',
      prompt: 'Creative viral latte art, beautiful coffee foam design, aesthetic minimalist cafe setting, artistic barista presentation, Instagram-worthy coffee, trending beverage art, perfect foam',
      style: 'artistic',
      platform: 'Instagram',
      tags: ['latte art', 'coffee art', 'viral beverage', 'cafe aesthetic', 'artistic'],
      cost: 50,
      unlockCost: 160,
      category: 'food',
      isActive: true,
    },
    {
      title: 'Plant Mom Aesthetic Viral',
      description: 'Mẹ của cây cảnh - trend đang viral trên lifestyle communities',
      prompt: 'Plant mom aesthetic, surrounded by lush houseplants, green thumb lifestyle, botanical home decoration, natural lighting, peaceful plant care moment, urban jungle vibes',
      style: 'natural',
      platform: 'Instagram',
      tags: ['plant mom', 'houseplants', 'botanical lifestyle', 'viral trend', 'green living'],
      cost: 52,
      unlockCost: 170,
      category: 'lifestyle',
      isActive: true,
    },
    {
      title: 'Vietnamese Iced Coffee Viral',
      description: 'Cà phê đá Việt Nam đang viral trên khắp thế giới',
      prompt: 'Authentic Vietnamese iced coffee, traditional drip filter phin, condensed milk, cultural beverage preparation, refreshing summer drink, coffee culture, authentic Vietnam experience',
      style: 'authentic',
      platform: 'Instagram',
      tags: ['vietnamese coffee', 'ca phe da', 'traditional drink', 'viral beverage', 'cultural'],
      cost: 53,
      unlockCost: 175,
      category: 'food',
      isActive: true,
    },
    {
      title: 'Neon Cyberpunk City Viral',
      description: 'Thành phố cyberpunk neon đang trending trong gaming và art',
      prompt: 'Cyberpunk neon city, futuristic skyline, purple blue neon lights, high-tech atmosphere, dystopian aesthetic, night scene, blade runner vibes, sci-fi urban landscape',
      style: 'cyberpunk',
      platform: 'Instagram',
      tags: ['cyberpunk', 'neon city', 'futuristic', 'viral aesthetic', 'sci-fi'],
      cost: 60,
      unlockCost: 200,
      category: 'technology',
      isActive: true,
    },
    {
      title: 'Matcha Everything Viral',
      description: 'Matcha trend đang viral trong mọi lĩnh vực từ food đến beauty',
      prompt: 'Matcha aesthetic everything, green tea powder art, Japanese zen culture, traditional tea ceremony, mindful moment, calming green tones, matcha latte art, cultural beverage',
      style: 'zen',
      platform: 'Instagram',
      tags: ['matcha trend', 'green tea', 'japanese culture', 'viral food', 'zen'],
      cost: 54,
      unlockCost: 175,
      category: 'food',
      isActive: true,
    },
    {
      title: 'Ethereal Forest Fairy Viral',
      description: 'Nàng tiên rừng huyền ảo viral trong fantasy art community',
      prompt: 'Ethereal mystical forest fairy, magical enchanted woodland setting, flowing ethereal dress, glittering fairy effects, mystical atmosphere, fantasy art style, enchanted forest background',
      style: 'fantasy',
      platform: 'Instagram',
      tags: ['forest fairy', 'ethereal fantasy', 'magical', 'viral art', 'mystical'],
      cost: 58,
      unlockCost: 190,
      category: 'art',
      isActive: true,
    },
    {
      title: 'Aesthetic Study Setup Viral',
      description: 'Bàn học aesthetic đang hot trend trong student communities',
      prompt: 'Aesthetic organized study setup, minimalist desk arrangement, cute stationery collection, natural lighting, motivational quotes, cozy study atmosphere, productivity vibes, student lifestyle',
      style: 'aesthetic',
      platform: 'Instagram',
      tags: ['study setup', 'student aesthetic', 'organized', 'viral lifestyle', 'productivity'],
      cost: 51,
      unlockCost: 165,
      category: 'lifestyle',
      isActive: true,
    },
    {
      title: 'Vietnamese Night Market Viral',
      description: 'Chợ đêm Việt Nam viral trên TikTok du lịch quốc tế',
      prompt: 'Vibrant Vietnamese night market, colorful traditional lanterns, street food vendors, bustling cultural atmosphere, authentic local life experience, food stalls, cultural tourism',
      style: 'vibrant',
      platform: 'TikTok',
      tags: ['vietnamese market', 'night market', 'cultural tourism', 'viral travel', 'authentic'],
      cost: 55,
      unlockCost: 180,
      category: 'travel',
      isActive: true,
    },
    {
      title: 'Retro Gaming Setup Viral',
      description: 'Setup game retro đang comeback mạnh trong gaming community',
      prompt: 'Nostalgic retro gaming setup, vintage game consoles, CRT monitor, 80s neon aesthetic, classic video games, nostalgic atmosphere, retro tech collection, gaming nostalgia',
      style: 'retro',
      platform: 'Instagram',
      tags: ['retro gaming', 'vintage tech', '80s nostalgia', 'viral setup', 'gaming'],
      cost: 57,
      unlockCost: 185,
      category: 'technology',
      isActive: true,
    },
    {
      title: 'Sunset Beach Vibes Viral',
      description: 'Cảnh hoàng hôn biển viral trên Instagram travel',
      prompt: 'Dreamy sunset beach vibes, golden hour lighting, peaceful ocean waves, silhouette figure, romantic atmosphere, vacation mood, travel photography, paradise aesthetic',
      style: 'romantic',
      platform: 'Instagram',
      tags: ['sunset beach', 'golden hour', 'travel vibes', 'viral travel', 'paradise'],
      cost: 52,
      unlockCost: 170,
      category: 'travel',
      isActive: true,
    },
    {
      title: 'Vietnamese Nón Lá Viral',
      description: 'Nón lá Việt Nam đang viral trong fashion quốc tế',
      prompt: 'Traditional Vietnamese conical hat non la, cultural heritage fashion, rural countryside rice fields background, authentic Vietnam culture, traditional craftsmanship, cultural pride',
      style: 'traditional',
      platform: 'Instagram',
      tags: ['non la', 'vietnamese culture', 'traditional fashion', 'viral heritage', 'authentic'],
      cost: 56,
      unlockCost: 180,
      category: 'fashion',
      isActive: true,
    },
    {
      title: 'Kawaii Bento Box Viral',
      description: 'Hộp cơm bento kawaii đang hot trend trong food art',
      prompt: 'Adorable kawaii bento box, cute food art characters, colorful Japanese lunch arrangement, Instagram-worthy presentation, anime-inspired food design, kawaii culture, food styling',
      style: 'kawaii',
      platform: 'Instagram',
      tags: ['kawaii bento', 'cute food art', 'japanese culture', 'viral food', 'anime'],
      cost: 53,
      unlockCost: 175,
      category: 'food',
      isActive: true,
    },
    {
      title: 'Digital Art Portrait Viral',
      description: 'Chân dung nghệ thuật số viral trong art communities',
      prompt: 'Stunning digital art portrait, vibrant neon colors, stylized illustration, modern contemporary art style, creative digital expression, artistic interpretation, digital painting technique',
      style: 'digital',
      platform: 'Instagram',
      tags: ['digital art', 'portrait art', 'vibrant colors', 'viral art', 'contemporary'],
      cost: 59,
      unlockCost: 195,
      category: 'art',
      isActive: true,
    },
    {
      title: 'Boho Chic Style Viral',
      description: 'Phong cách boho chic đang comeback trong fashion',
      prompt: 'Bohemian chic fashion style, flowing natural fabrics, earth tone colors, natural textures, free-spirited boho style, artistic accessories, hippie aesthetic, natural beauty',
      style: 'bohemian',
      platform: 'Instagram',
      tags: ['boho chic', 'bohemian style', 'free spirit', 'viral fashion', 'natural'],
      cost: 58,
      unlockCost: 190,
      category: 'fashion',
      isActive: true,
    },
    {
      title: 'Vietnamese Coffee Shop Viral',
      description: 'Quán cà phê Việt Nam aesthetic viral trên du lịch quốc tế',
      prompt: 'Charming Vietnamese coffee shop aesthetic, traditional colonial architecture, wooden furniture, cozy cultural ambiance, authentic design, coffee culture, local atmosphere, cultural tourism',
      style: 'cozy',
      platform: 'Instagram',
      tags: ['vietnamese cafe', 'coffee culture', 'traditional architecture', 'viral tourism', 'authentic'],
      cost: 60,
      unlockCost: 200,
      category: 'lifestyle',
      isActive: true,
    },
    {
      title: 'Vintage Film Camera Viral',
      description: 'Máy ảnh film vintage đang comeback trong photography',
      prompt: 'Nostalgic vintage film camera aesthetic, retro analog photography, warm film tones, artistic composition, analog photography revival, vintage tech collection, photography nostalgia',
      style: 'vintage',
      platform: 'Instagram',
      tags: ['vintage camera', 'film photography', 'retro tech', 'viral photography', 'nostalgic'],
      cost: 56,
      unlockCost: 180,
      category: 'art',
      isActive: true,
    },
    {
      title: 'Minimalist Room Decor Viral',
      description: 'Phong cách decor phòng tối giản trending worldwide',
      prompt: 'Minimalist bedroom decor, clean geometric lines, neutral color palette, houseplants, natural lighting, Scandinavian influence, peaceful atmosphere, modern aesthetic lifestyle',
      style: 'minimalist',
      platform: 'Instagram',
      tags: ['minimalist decor', 'scandinavian style', 'clean aesthetic', 'viral interior', 'modern'],
      cost: 54,
      unlockCost: 175,
      category: 'lifestyle',
      isActive: true,
    },
    
    // Additional Premium Templates
    {
      title: 'Professional Headshot Premium',
      description: 'Ảnh chân dung chuyên nghiệp cao cấp',
      prompt: 'Premium professional headshot, executive business attire, confident expression, studio lighting, corporate leadership style, high-quality portrait photography',
      style: 'professional',
      platform: 'LinkedIn',
      tags: ['professional', 'executive', 'business', 'premium'],
      cost: 45,
      unlockCost: 150,
      category: 'business',
      isActive: true,
    },
    {
      title: 'Food Photography Premium',
      description: 'Chụp ảnh món ăn chuyên nghiệp cao cấp',
      prompt: 'Premium restaurant food photography, gourmet presentation, professional lighting, appetizing composition, michelin star quality, culinary art photography',
      style: 'gourmet',
      platform: 'Instagram',
      tags: ['food photography', 'gourmet', 'premium', 'restaurant'],
      cost: 48,
      unlockCost: 155,
      category: 'food',
      isActive: true,
    },
    {
      title: 'Travel Photography Premium',
      description: 'Ảnh du lịch cao cấp cho travel bloggers',
      prompt: 'Premium travel photography, exotic destinations, professional travel documentation, stunning landscapes, luxury travel experience, wanderlust inspiration',
      style: 'luxury',
      platform: 'Instagram',
      tags: ['travel', 'luxury', 'destinations', 'premium'],
      cost: 50,
      unlockCost: 160,
      category: 'travel',
      isActive: true,
    },
    {
      title: 'Fashion Portrait Premium',
      description: 'Chân dung thời trang cao cấp editorial',
      prompt: 'High-end fashion portrait, editorial styling, luxury brands, professional model photography, high fashion aesthetic, magazine quality photography',
      style: 'editorial',
      platform: 'Instagram',
      tags: ['fashion', 'editorial', 'luxury', 'premium'],
      cost: 55,
      unlockCost: 170,
      category: 'fashion',
      isActive: true,
    },
    {
      title: 'Tech Product Photography',
      description: 'Chụp sản phẩm công nghệ chuyên nghiệp',
      prompt: 'Premium tech product photography, modern gadgets, sleek design showcase, innovative technology presentation, commercial quality, professional lighting',
      style: 'commercial',
      platform: 'Website',
      tags: ['technology', 'products', 'commercial', 'professional'],
      cost: 52,
      unlockCost: 165,
      category: 'technology',
      isActive: true,
    },
    {
      title: 'Interior Design Premium',
      description: 'Thiết kế nội thất cao cấp luxury',
      prompt: 'Luxury interior design, high-end furniture, premium materials, sophisticated aesthetic, architectural photography, designer spaces, luxury lifestyle',
      style: 'luxury',
      platform: 'Instagram',
      tags: ['interior design', 'luxury', 'premium', 'sophisticated'],
      cost: 58,
      unlockCost: 180,
      category: 'lifestyle',
      isActive: true,
    },
    {
      title: 'Abstract Art Premium',
      description: 'Nghệ thuật trừu tượng cao cấp modern art',
      prompt: 'Premium abstract art, contemporary design, bold color compositions, artistic expression, modern gallery style, creative interpretation, fine art photography',
      style: 'contemporary',
      platform: 'Instagram',
      tags: ['abstract art', 'contemporary', 'premium', 'gallery'],
      cost: 56,
      unlockCost: 175,
      category: 'art',
      isActive: true,
    },
    {
      title: 'Wedding Photography Premium',
      description: 'Ảnh cưới cao cấp luxury wedding',
      prompt: 'Luxury wedding photography, romantic couple portraits, elegant ceremony documentation, premium wedding aesthetic, love story photography, high-end wedding style',
      style: 'luxury',
      platform: 'Instagram',
      tags: ['wedding', 'luxury', 'romantic', 'premium'],
      cost: 60,
      unlockCost: 185,
      category: 'lifestyle',
      isActive: true,
    },
    {
      title: 'Brand Photography Premium',
      description: 'Ảnh thương hiệu cao cấp corporate',
      prompt: 'Premium brand photography, corporate identity, professional branding, company image, executive lifestyle, business success, corporate excellence',
      style: 'corporate',
      platform: 'Website',
      tags: ['branding', 'corporate', 'premium', 'professional'],
      cost: 55,
      unlockCost: 170,
      category: 'business',
      isActive: true,
    },
    {
      title: 'Luxury Lifestyle Premium',
      description: 'Phong cách sống xa hoa cao cấp',
      prompt: 'Luxury lifestyle photography, high-end products, elegant settings, premium quality, sophisticated living, exclusive experiences, luxury brand aesthetic',
      style: 'luxury',
      platform: 'Instagram',
      tags: ['luxury', 'lifestyle', 'premium', 'exclusive'],
      cost: 60,
      unlockCost: 190,
      category: 'lifestyle',
      isActive: true,
    },
    {
      title: 'Artistic Portrait Premium',
      description: 'Chân dung nghệ thuật cao cấp creative',
      prompt: 'Premium artistic portrait, creative lighting techniques, dramatic shadows, artistic expression, fine art photography, professional portrait artistry',
      style: 'artistic',
      platform: 'Instagram',
      tags: ['artistic', 'portrait', 'creative', 'premium'],
      cost: 57,
      unlockCost: 180,
      category: 'art',
      isActive: true,
    },
    {
      title: 'Architecture Photography Premium',
      description: 'Ảnh kiến trúc cao cấp professional',
      prompt: 'Premium architectural photography, modern buildings, geometric designs, urban architecture, structural beauty, professional architectural documentation',
      style: 'architectural',
      platform: 'Instagram',
      tags: ['architecture', 'modern', 'geometric', 'premium'],
      cost: 54,
      unlockCost: 175,
      category: 'art',
      isActive: true,
    },
    {
      title: 'Commercial Photography Premium',
      description: 'Ảnh thương mại cao cấp marketing',
      prompt: 'Premium commercial photography, marketing ready, brand messaging, commercial success, professional advertising, high-end commercial content',
      style: 'commercial',
      platform: 'Website',
      tags: ['commercial', 'marketing', 'advertising', 'premium'],
      cost: 53,
      unlockCost: 170,
      category: 'business',
      isActive: true,
    },
    {
      title: 'Nature Photography Premium',
      description: 'Ảnh thiên nhiên cao cấp landscape',
      prompt: 'Premium nature photography, breathtaking landscapes, natural beauty, wilderness photography, environmental artistry, scenic landscape photography',
      style: 'scenic',
      platform: 'Instagram',
      tags: ['nature', 'landscape', 'scenic', 'premium'],
      cost: 51,
      unlockCost: 165,
      category: 'travel',
      isActive: true,
    },
    {
      title: 'Creative Content Premium',
      description: 'Nội dung sáng tạo cao cấp viral',
      prompt: 'Premium creative content, original concepts, artistic interpretation, innovative ideas, creative excellence, high-quality content creation',
      style: 'creative',
      platform: 'Instagram',
      tags: ['creative', 'original', 'innovative', 'premium'],
      cost: 59,
      unlockCost: 185,
      category: 'art',
      isActive: true,
    },
    {
      title: 'Pilates Princess Viral',
      description: 'Pilates girl aesthetic đang hot trend trên fitness community',
      prompt: 'Pilates princess aesthetic, elegant yoga pose, pastel activewear, zen studio setting, graceful movement, mindful fitness, soft natural lighting, wellness lifestyle',
      style: 'elegant',
      platform: 'Instagram',
      tags: ['pilates', 'fitness girl', 'wellness', 'viral lifestyle', 'zen'],
      cost: 54,
      unlockCost: 175,
      category: 'lifestyle',
      isActive: true,
    },
    {
      title: 'Gym Girl Motivation Viral',
      description: 'Gym girl motivation đang viral trên fitness TikTok',
      prompt: 'Strong gym girl motivation, powerful workout pose, athletic wear, modern gym equipment, determined expression, fitness inspiration, energetic lighting, strength training',
      style: 'powerful',
      platform: 'TikTok',
      tags: ['gym girl', 'fitness motivation', 'viral workout', 'strong woman', 'athletic'],
      cost: 55,
      unlockCost: 180,
      category: 'lifestyle',
      isActive: true,
    },
    {
      title: 'Van Life Adventure Viral',
      description: 'Van life adventure đang viral trên travel communities',
      prompt: 'Van life adventure aesthetic, cozy mobile home interior, mountain landscape view, minimalist travel lifestyle, freedom road trip, wanderlust vibes, sunset golden hour',
      style: 'adventurous',
      platform: 'Instagram',
      tags: ['van life', 'adventure travel', 'nomad lifestyle', 'viral travel', 'freedom'],
      cost: 56,
      unlockCost: 180,
      category: 'travel',
      isActive: true,
    },
    {
      title: 'Solo Travel Girl Viral',
      description: 'Solo travel girl đang trending mạnh trên social media',
      prompt: 'Confident solo travel girl, beautiful destination backdrop, adventurous spirit, cultural exploration, independent woman, wanderlust inspiration, travel photography aesthetic',
      style: 'confident',
      platform: 'Instagram',
      tags: ['solo travel', 'independent woman', 'viral travel', 'adventure', 'wanderlust'],
      cost: 57,
      unlockCost: 185,
      category: 'travel',
      isActive: true,
    },
    {
      title: 'Resin Art Creation Viral',
      description: 'Resin art creation đang viral trong art communities',
      prompt: 'Mesmerizing resin art creation process, colorful fluid patterns, artistic workspace, creative hands-on process, modern art technique, Instagram-worthy craft, artistic expression',
      style: 'artistic',
      platform: 'Instagram',
      tags: ['resin art', 'art creation', 'viral art', 'creative process', 'modern craft'],
      cost: 58,
      unlockCost: 190,
      category: 'art',
      isActive: true,
    },
    
    // TRANSFORM TEMPLATES (30 templates) - Viral Trends
    {
      title: 'Mermaid Princess Transform',
      description: 'Biến thành nàng tiên cá với đuôi cá lấp lánh viral',
      prompt: 'Transform into magical mermaid princess, shimmering scales, flowing underwater hair, ocean goddess aesthetic, fantasy underwater kingdom, ethereal aquatic beauty, pearl accessories',
      style: 'fantasy',
      platform: 'TikTok',
      tags: ['mermaid', 'transformation', 'viral trend', 'fantasy', 'underwater'],
      cost: 60,
      unlockCost: 180,
      category: 'transform',
      type: 'TRANSFORM',
      requiresUpload: true,
      isActive: true,
    },
    {
      title: 'Kitten Shadow Transform',
      description: 'Hiệu ứng kitten shadow viral đang hot trên TikTok',
      prompt: 'Transform with cute kitten shadow effect, playful cat ears shadow, kawaii aesthetic, soft pink lighting, adorable kitten silhouette behind person, cute cat girl transformation',
      style: 'cute',
      platform: 'TikTok',
      tags: ['kitten shadow', 'cat ears', 'viral effect', 'kawaii', 'cute transformation'],
      cost: 54,
      unlockCost: 170,
      category: 'transform',
      type: 'TRANSFORM',
      requiresUpload: true,
      isActive: true,
    },
    {
      title: 'Vintage Film Camera Transform',
      description: 'Biến ảnh thành vintage film camera aesthetic',
      prompt: 'Transform to vintage film camera aesthetic, retro grain texture, warm sepia tones, nostalgic 80s vibe, old film photography style, vintage color grading',
      style: 'vintage',
      platform: 'Instagram',
      tags: ['vintage', 'film camera', 'retro', 'nostalgic', 'aesthetic'],
      cost: 110,
      unlockCost: 165,
      category: 'transform',
      type: 'TRANSFORM',
      requiresUpload: true,
      isActive: true,
    },
    {
      title: 'Angel Wings Transform',
      description: 'Thêm đôi cánh thiên thần lấp lánh viral',
      prompt: 'Transform with beautiful angel wings, ethereal feathered wings, heavenly glow effect, divine lighting, celestial transformation, angelic aura, golden light rays',
      style: 'ethereal',
      platform: 'Instagram',
      tags: ['angel wings', 'ethereal', 'heavenly', 'viral transformation', 'divine'],
      cost: 130,
      unlockCost: 185,
      category: 'transform',
      type: 'TRANSFORM',
      requiresUpload: true,
      isActive: true,
    },
    {
      title: 'Cyberpunk Neon Transform',
      description: 'Biến thành cyberpunk với neon effects viral',
      prompt: 'Transform into cyberpunk character, neon glow effects, futuristic digital overlay, cybernetic enhancements, purple blue neon lighting, sci-fi transformation',
      style: 'cyberpunk',
      platform: 'TikTok',
      tags: ['cyberpunk', 'neon', 'futuristic', 'sci-fi', 'digital'],
      cost: 135,
      unlockCost: 190,
      category: 'transform',
      type: 'TRANSFORM',
      requiresUpload: true,
      isActive: true,
    },
    {
      title: 'Fairy Forest Transform',
      description: 'Biến thành nàng tiên rừng với hiệu ứng ma thuật',
      prompt: 'Transform into mystical forest fairy, magical sparkles, enchanted forest background, fairy dust effects, woodland sprite transformation, mystical glow',
      style: 'magical',
      platform: 'Instagram',
      tags: ['fairy', 'forest', 'magical', 'enchanted', 'mystical'],
      cost: 125,
      unlockCost: 180,
      category: 'transform',
      type: 'TRANSFORM',
      requiresUpload: true,
      isActive: true,
    },
    {
      title: 'Anime Character Transform',
      description: 'Biến thành nhân vật anime với big eyes viral',
      prompt: 'Transform into anime character, large expressive eyes, anime art style, manga aesthetic, kawaii features, colorful anime hair, Japanese animation style',
      style: 'anime',
      platform: 'TikTok',
      tags: ['anime', 'manga', 'kawaii', 'big eyes', 'japanese'],
      cost: 120,
      unlockCost: 175,
      category: 'transform',
      type: 'TRANSFORM',
      requiresUpload: true,
      isActive: true,
    },
    {
      title: 'Glass Skin K-Beauty Transform',
      description: 'Làn da thủy tinh K-beauty transformation viral',
      prompt: 'Transform with perfect glass skin effect, dewy Korean beauty glow, flawless porcelain skin, K-beauty transformation, radiant complexion, skincare glow up',
      style: 'beauty',
      platform: 'Instagram',
      tags: ['glass skin', 'k-beauty', 'korean', 'dewy', 'skincare'],
      cost: 105,
      unlockCost: 160,
      category: 'transform',
      type: 'TRANSFORM',
      requiresUpload: true,
      isActive: true,
    },
    {
      title: 'Galaxy Space Transform',
      description: 'Biến thành goddess vũ trụ với galaxy effects',
      prompt: 'Transform into cosmic galaxy goddess, nebula hair effects, starry cosmic background, celestial transformation, space goddess aesthetic, galaxy colors',
      style: 'cosmic',
      platform: 'Instagram',
      tags: ['galaxy', 'space', 'cosmic', 'nebula', 'celestial'],
      cost: 140,
      unlockCost: 195,
      category: 'transform',
      type: 'TRANSFORM',
      requiresUpload: true,
      isActive: true,
    },
    {
      title: 'Butterfly Wings Transform',
      description: 'Thêm đôi cánh bướm lấp lánh viral trên TikTok',
      prompt: 'Transform with beautiful butterfly wings, colorful wing patterns, magical butterfly transformation, nature goddess aesthetic, fluttering wing effects',
      style: 'nature',
      platform: 'TikTok',
      tags: ['butterfly', 'wings', 'colorful', 'nature', 'magical'],
      cost: 115,
      unlockCost: 170,
      category: 'transform',
      type: 'TRANSFORM',
      requiresUpload: true,
      isActive: true,
    },
    {
      title: 'Fire Phoenix Transform',
      description: 'Biến thành phoenix lửa với hiệu ứng cháy epic',
      prompt: 'Transform into fire phoenix, burning flame effects, phoenix fire wings, rebirth transformation, dramatic fire aesthetic, mythical phoenix power',
      style: 'epic',
      platform: 'Instagram',
      tags: ['phoenix', 'fire', 'flames', 'mythical', 'epic'],
      cost: 145,
      unlockCost: 200,
      category: 'transform',
      type: 'TRANSFORM',
      requiresUpload: true,
      isActive: true,
    },
    {
      title: 'Ice Queen Transform',
      description: 'Biến thành nữ hoàng băng giá với crystal effects',
      prompt: 'Transform into ice queen, crystal ice effects, frozen goddess aesthetic, winter queen transformation, icy blue aura, snow queen powers',
      style: 'ice',
      platform: 'Instagram',
      tags: ['ice queen', 'crystal', 'frozen', 'winter', 'goddess'],
      cost: 135,
      unlockCost: 190,
      category: 'transform',
      type: 'TRANSFORM',
      requiresUpload: true,
      isActive: true,
    },
    {
      title: 'Holographic Shimmer Transform',
      description: 'Hiệu ứng holographic shimmer viral trên social media',
      prompt: 'Transform with holographic shimmer effect, iridescent rainbow colors, metallic hologram overlay, futuristic transformation, prismatic glow effects',
      style: 'holographic',
      platform: 'Instagram',
      tags: ['holographic', 'shimmer', 'rainbow', 'iridescent', 'metallic'],
      cost: 125,
      unlockCost: 180,
      category: 'transform',
      type: 'TRANSFORM',
      requiresUpload: true,
      isActive: true,
    },
    {
      title: 'Dragon Goddess Transform',
      description: 'Biến thành nữ thần rồng với scales và horns',
      prompt: 'Transform into dragon goddess, dragon scales skin, mystical horns, powerful dragon transformation, reptilian beauty, mythical dragon aesthetic',
      style: 'mythical',
      platform: 'TikTok',
      tags: ['dragon', 'goddess', 'scales', 'mythical', 'powerful'],
      cost: 140,
      unlockCost: 195,
      category: 'transform',
      type: 'TRANSFORM',
      requiresUpload: true,
      isActive: true,
    },
    {
      title: 'Glitch Digital Transform',
      description: 'Hiệu ứng glitch digital viral trong tech community',
      prompt: 'Transform with digital glitch effects, pixelated distortion, cybernetic malfunction aesthetic, digital corruption art, tech virus transformation',
      style: 'digital',
      platform: 'TikTok',
      tags: ['glitch', 'digital', 'pixelated', 'tech', 'cyber'],
      cost: 120,
      unlockCost: 175,
      category: 'transform',
      type: 'TRANSFORM',
      requiresUpload: true,
      isActive: true,
    },
    {
      title: 'Flower Crown Princess Transform',
      description: 'Biến thành công chúa với vương miện hoa tươi',
      prompt: 'Transform into flower crown princess, beautiful fresh flower crown, spring goddess aesthetic, floral princess transformation, nature queen vibes',
      style: 'floral',
      platform: 'Instagram',
      tags: ['flower crown', 'princess', 'floral', 'spring', 'nature'],
      cost: 110,
      unlockCost: 165,
      category: 'transform',
      type: 'TRANSFORM',
      requiresUpload: true,
      isActive: true,
    },
    {
      title: 'Vampire Gothic Transform',
      description: 'Biến thành vampire gothic với fangs và dark makeup',
      prompt: 'Transform into gothic vampire, vampire fangs, dark gothic makeup, blood red aesthetic, mysterious vampire transformation, gothic beauty',
      style: 'gothic',
      platform: 'TikTok',
      tags: ['vampire', 'gothic', 'fangs', 'dark', 'mysterious'],
      cost: 130,
      unlockCost: 185,
      category: 'transform',
      type: 'TRANSFORM',
      requiresUpload: true,
      isActive: true,
    },
    {
      title: 'Sailor Moon Transform',
      description: 'Biến thành Sailor Moon với tiara và costume',
      prompt: 'Transform into Sailor Moon character, magical girl transformation, sailor outfit, moon tiara, anime magical girl aesthetic, kawaii sailor uniform',
      style: 'anime',
      platform: 'TikTok',
      tags: ['sailor moon', 'magical girl', 'anime', 'kawaii', 'transformation'],
      cost: 125,
      unlockCost: 180,
      category: 'transform',
      type: 'TRANSFORM',
      requiresUpload: true,
      isActive: true,
    },
    {
      title: 'Mermaid Scales Makeup Transform',
      description: 'Hiệu ứng vảy cá trên mặt viral makeup trend',
      prompt: 'Transform with mermaid scales makeup, iridescent face scales, aquatic beauty transformation, ocean princess makeup, shimmering scale patterns',
      style: 'beauty',
      platform: 'Instagram',
      tags: ['mermaid scales', 'makeup', 'iridescent', 'aquatic', 'beauty'],
      cost: 115,
      unlockCost: 170,
      category: 'transform',
      type: 'TRANSFORM',
      requiresUpload: true,
      isActive: true,
    },
    {
      title: 'Crystal Gem Transform',
      description: 'Biến thành crystal gem với đá quý trên da',
      prompt: 'Transform into crystal gem being, embedded crystals in skin, gemstone transformation, mineral goddess aesthetic, crystalline beauty effects',
      style: 'crystal',
      platform: 'Instagram',
      tags: ['crystal', 'gemstone', 'mineral', 'embedded', 'goddess'],
      cost: 135,
      unlockCost: 190,
      category: 'transform',
      type: 'TRANSFORM',
      requiresUpload: true,
      isActive: true,
    },
    {
      title: 'Witch Magic Transform',
      description: 'Biến thành phù thủy với magic effects và hat',
      prompt: 'Transform into magical witch, witch hat, magical aura effects, spellcasting transformation, mystical witch aesthetic, magical powers visualization',
      style: 'magical',
      platform: 'TikTok',
      tags: ['witch', 'magic', 'spells', 'mystical', 'supernatural'],
      cost: 120,
      unlockCost: 175,
      category: 'transform',
      type: 'TRANSFORM',
      requiresUpload: true,
      isActive: true,
    },
    {
      title: 'Neon Rave Transform',
      description: 'Biến thành rave girl với neon paint và glow',
      prompt: 'Transform into neon rave party aesthetic, UV reactive body paint, glow stick effects, electronic dance transformation, festival rave vibes',
      style: 'neon',
      platform: 'TikTok',
      tags: ['neon', 'rave', 'glow', 'festival', 'party'],
      cost: 110,
      unlockCost: 165,
      category: 'transform',
      type: 'TRANSFORM',
      requiresUpload: true,
      isActive: true,
    },
    {
      title: 'Forest Elf Transform',
      description: 'Biến thành elf rừng với pointed ears và nature',
      prompt: 'Transform into mystical forest elf, pointed elf ears, woodland transformation, nature spirit aesthetic, elven beauty with forest magic',
      style: 'fantasy',
      platform: 'Instagram',
      tags: ['elf', 'forest', 'pointed ears', 'woodland', 'nature'],
      cost: 125,
      unlockCost: 180,
      category: 'transform',
      type: 'TRANSFORM',
      requiresUpload: true,
      isActive: true,
    },
    {
      title: 'Robot Cyborg Transform',
      description: 'Biến thành cyborg với mechanical parts viral',
      prompt: 'Transform into futuristic cyborg, mechanical implants, robotic transformation, cybernetic enhancements, sci-fi android aesthetic',
      style: 'sci-fi',
      platform: 'TikTok',
      tags: ['cyborg', 'robot', 'mechanical', 'cybernetic', 'android'],
      cost: 140,
      unlockCost: 195,
      category: 'transform',
      type: 'TRANSFORM',
      requiresUpload: true,
      isActive: true,
    },
    {
      title: 'Unicorn Horn Transform',
      description: 'Thêm sừng unicorn lấp lánh với rainbow mane',
      prompt: 'Transform with magical unicorn horn, rainbow colored mane, unicorn transformation, mythical creature aesthetic, magical horn with sparkles',
      style: 'magical',
      platform: 'TikTok',
      tags: ['unicorn', 'horn', 'rainbow', 'mythical', 'sparkles'],
      cost: 115,
      unlockCost: 170,
      category: 'transform',
      type: 'TRANSFORM',
      requiresUpload: true,
      isActive: true,
    },
    {
      title: 'Demon Horns Transform',
      description: 'Biến thành demon với horns và dark aura',
      prompt: 'Transform into powerful demon, demon horns, dark supernatural aura, infernal transformation, hellish beauty aesthetic, demonic powers',
      style: 'dark',
      platform: 'TikTok',
      tags: ['demon', 'horns', 'dark', 'supernatural', 'infernal'],
      cost: 135,
      unlockCost: 190,
      category: 'transform',
      type: 'TRANSFORM',
      requiresUpload: true,
      isActive: true,
    },
    {
      title: 'Pastel Goth Transform',
      description: 'Biến thành pastel goth với cute dark aesthetic',
      prompt: 'Transform into pastel goth aesthetic, cute dark makeup, pastel colors with gothic elements, kawaii goth transformation, soft gothic beauty',
      style: 'pastel-goth',
      platform: 'Instagram',
      tags: ['pastel goth', 'kawaii', 'cute dark', 'gothic', 'aesthetic'],
      cost: 120,
      unlockCost: 175,
      category: 'transform',
      type: 'TRANSFORM',
      requiresUpload: true,
      isActive: true,
    },
    {
      title: 'Star Constellation Transform',
      description: 'Biến thành constellation map trên da viral trend',
      prompt: 'Transform with constellation map on skin, star patterns, celestial body art, astrology transformation, cosmic star mapping on face and body',
      style: 'celestial',
      platform: 'Instagram',
      tags: ['constellation', 'stars', 'celestial', 'astrology', 'cosmic'],
      cost: 130,
      unlockCost: 185,
      category: 'transform',
      type: 'TRANSFORM',
      requiresUpload: true,
      isActive: true,
    },
    {
      title: 'Vintage Doll Transform',
      description: 'Biến thành vintage porcelain doll với doll makeup',
      prompt: 'Transform into vintage porcelain doll, doll-like makeup, rosy cheeks, doll eyes, antique toy aesthetic, classic vintage doll transformation',
      style: 'vintage',
      platform: 'TikTok',
      tags: ['vintage doll', 'porcelain', 'antique', 'toy', 'classic'],
      cost: 125,
      unlockCost: 180,
      category: 'transform',
      type: 'TRANSFORM',
      requiresUpload: true,
      isActive: true,
    },
    {
      title: 'Rainbow Hair Transform',
      description: 'Biến tóc thành rainbow colors viral trên TikTok',
      prompt: 'Transform hair into vibrant rainbow colors, multicolor hair transformation, gradient rainbow effect, magical color changing hair, prismatic hair aesthetic, unicorn hair trend',
      style: 'colorful',
      platform: 'TikTok',
      tags: ['rainbow hair', 'colorful', 'viral hair', 'unicorn', 'transformation'],
      cost: 110,
      unlockCost: 165,
      category: 'transform',
      type: 'TRANSFORM',
      requiresUpload: true,
      isActive: true,
    }
  ]

  console.log('🎨 Creating premium viral templates...')
  const createdTemplates = []
  for (const template of templates) {
    const createdTemplate = await prisma.template.create({
      data: template,
    })
    createdTemplates.push(createdTemplate)
    console.log(`✅ Created: ${template.title}`)
  }

  // Create initial token transaction for the user
  await prisma.tokenTransaction.create({
    data: {
      userId: defaultUser.id,
      amount: 5000,
      type: 'EARNED',
      description: 'Welcome bonus - Premium package',
      createdAt: new Date(),
    },
  })

  const viralCount = templates.filter(t => t.cost >= 50).length
  const premiumCount = templates.filter(t => t.unlockCost >= 150).length
  
  console.log('🎉 Database seeded successfully!')
  console.log(`📊 Created ${templates.length} premium templates`)
  console.log(`🔥 Viral trends (50+ cost tokens): ${viralCount}`)
  console.log(`💎 Premium unlock (150+ tokens): ${premiumCount}`)
  console.log(`💰 Cost range: ${Math.min(...templates.map(t => t.cost))}-${Math.max(...templates.map(t => t.cost))} tokens`)
  console.log(`🔓 Unlock range: ${Math.min(...templates.map(t => t.unlockCost))}-${Math.max(...templates.map(t => t.unlockCost))} tokens`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  }) 